USE AUTH;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS T_RESOURCES;
CREATE TABLE T_RESOURCES (
  ID INT NOT NULL AUTO_INCREMENT COMMENT '自增长ID',
  RESOURCE_NAME VARCHAR(45) NULL COMMENT '资源名称',
  RESOURCE_URL VARCHAR(100) NULL COMMENT '资源路径',
  CONTENT VARCHAR(300) NULL COMMENT '描述',
  PRIMARY KEY (ID),
  UNIQUE INDEX ID_UNIQUE (ID ASC));
