USE AUTH;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS T_ROLE;
CREATE TABLE T_ROLE (
  ID INT NOT NULL AUTO_INCREMENT COMMENT '自增长ID',
  ROLE_NAME VARCHAR(50) NOT NULL COMMENT '角色名称',
  PRIMARY KEY (ID),
  UNIQUE INDEX ID_UNIQUE (ID ASC));
