USE AUTH;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS T_USER_ROLE;
CREATE TABLE T_USER_ROLE (
  id int(11) NOT NULL AUTO_INCREMENT,
  user_id int(11) NOT NULL,
  role_id int(11) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY id_UNIQUE (id),
  KEY userId_idx (user_id),
  KEY role_id_idx (role_id),
  CONSTRAINT role_id FOREIGN KEY (role_id) REFERENCES T_ROLE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT user_id FOREIGN KEY (user_id) REFERENCES T_USER (id) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户角色关系表';
